<div class="wrapper pageAbout">

    <h1>Me découvrir</h1>

    <div class="content">
        <div class="adressTop">
            <img src="./public/medias/img/vincent.webp" alt="vincent petit">
            <div class="txt">
                <h2>Contact :</h2>
                <aside class="coords">
                    <address>
                        <p>Vincent Petit<br>
                            La Gaillardière,<br>
                            85 220 COMMEQUIER</p>
                        email : <a href="mailto:v-petit@gmx.fr">v-petit@gmx.fr</a> <br>
                        <i class="fa-solid fa-phone"></i> <a href="tel:+33686065972">06 86 06 59 72</a>
                    </address>

                    <div class="networks">
                        <a href="https://fr-fr.facebook.com/people/Vincent-PETIT-Apiculteur/100063510132602/" aria-label="Retrouvez-moi sur facebook" class="fa-brands fa-facebook"></a>
                    </div>
                </aside>
            </div>
        </div>

        <div class="zoomBas">
            <h2>En action: </h2>
            <div class="videoWrapper">
                <video controls autoplay>
                    <source src="public/medias/video/video_01.mp4" type="video/mp4">
                    <p>Votre navigateur ne prend pas en charge cette vidéo.</p>
                </video>
            </div>
        </div>
    </div>

</div>