<!-- Modal d'affichage de l'image en grand -->
<div class="modal-window"></div>

<?php foreach ($data['input'][1] as $key => $valeur) : ?>
    <article>
        <h2 class="articleTitle"><?= htmlspecialchars($valeur["productName"]); ?></h2>
        <?php if (($valeur['picture']) !== 'default.png') : ?>
            <div class="contImg modal-trigger zoom">
                <img src='public/uploads/<?= htmlspecialchars($valeur['picture']); ?>' alt="petite photo <?= htmlspecialchars($valeur["productName"]); ?>">
            </div>
        <?php else : ?>
            <div class="contImg">
                <img src='public/uploads/<?= htmlspecialchars($valeur['picture']); ?>' alt="petite photo <?= htmlspecialchars($valeur["productName"]); ?>">
            </div>
        <?php endif; ?>

        <div class="textProd">
            <div>
                <p><?= nl2br((htmlspecialchars($valeur["teaser"])),false); ?></p>
            </div>
            <div>
                <p><?= nl2br((htmlspecialchars($valeur["description"])),false); ?></p>
            </div>
            <div class="price">
                <!-- verification de l'existance d'items actifs -->
                <?php if (!empty($valeur['items'])) : ?>
                    Conditionnement&nbsp;:
                    <select class='selectItems' name='item' id=<?= "idFormItem" . htmlspecialchars($valeur['id_product']); ?>>
                        <?php foreach ($valeur['items'] as $key => $item) : ?>
                            <?php if ($valeur['id_product'] == $item['id_product']) : ?>
                                <option value="<?= htmlspecialchars($item["id_item"]); ?>"><?= htmlspecialchars($item["pack"]); ?></option>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </select>
                    <!-- // zone d'affichage du prix -->
                    <span id=<?= "idPrix" . htmlspecialchars($valeur['id_product']); ?>>
                        <span class="insec spanPrix"> Prix : <?= htmlspecialchars($valeur['items'][0]['price']) ?> Euros</span>
                    </span>
                <?php endif; ?>
            </div>
        </div>
    </article>
<?php endforeach; ?>