<div class="background">
    <div class="wrapper foot">

        <img class="alvFoot" src="./public/medias/img/alveole_fond_transparent.png" alt="alveoles stylisées">

        <div class="logoEtTitre">
            <a href="index.php?route=homePage&action=init" class="txtEtLogo">
                <span>Vincent Petit</span>
            </a>
            <p>
                Eleveur, production artisanale de miels et produits dérivés <span class="noWrap">- 85600 Commequier -</span>
            </p>
            <div class="networks">
                <a href="https://fr-fr.facebook.com/people/Vincent-PETIT-Apiculteur/100063510132602/" aria-label="Retrouvez-moi sur facebook" class=" fa-brands fa-facebook"></a>
            </div>
            <p class="small">
                <a href="index.php?view=mentions">Mentions légales</a> <span class="noWrap"> &copy;Vincent Petit 2023</span>
            </p>
        </div>

        <img class="alvFoot" src="./public/medias/img/alveole_fond_transparent.png" alt="alveoles stylisées">

    </div>
</div>


<!-- <a href="index.php?view=homePage">Home </a>
<a href="index.php?view=mentions">Mentions Légales</a>
<a href="index.php?route=user&action=displayFormRegister">register </a>
<a href="index.php?route=homePage&action=init"> *** Test ***</a>
<a href="index.php?route=products&action=displayFormProducts"> === Gestion des produits </a>
<a href="index.php?route=products&action=displayFormAddProducts"> === Ajout produit</a> -->