<h1>Création d'un compte !</h1>
<?php require_once('errors.inc.phtml'); ?>

<form action="?route=user&action=register" method="POST">

    <fieldset>
        <legend>Merci de renseigner les information suivantes :</legend>

        <input id="token" name="token" type="hidden" value="<?= $data['input'] ?>">

        <div class="formAdmin">
            <div class="grid">
                <label for="firstname">Votre prénom</label>
                <input type="text" id="firstname" name="firstname" minlength="2" maxlength="30" autofocus placeholder="autorisés lettres, espaces, ' et -" pattern="^[a-zA-Z '-]+$" required title="autorisés lettres, espaces, ' et -" value="<?php echo (isset($_POST['firstname'])) ? ($_POST['firstname']) : ""; ?>">

                <!-- entre 2 et 30 caractères - pattern : lettres, espaces, tirets et apostrophes -->
                <label for="lastname">Votre nom</label>
                <input type="text" id="lastname" name="lastname" minlength="2" maxlength="50" placeholder="autorisés lettres, espaces, ' et -" pattern="^[a-zA-Z '-]+$" required title="autorisés lettres, espaces, ' et -" value="<?php echo (isset($_POST['lastname'])) ? ($_POST['lastname']) : ""; ?>">

                <label for="email">Votre email</label>
                <input type="email" id="email" name="email" maxlength="50" required value="<?php echo (isset($_POST['email'])) ? ($_POST['email']) : ""; ?>">

                <label for="password">Un mot de passe</label>
                <div>
                    <input type="password" id="password" name="password" title="8/30 caract,  Maj +Min +Chiffre+ caractère spécial " placeholder="8/30 caract,  Maj +Min +Chiffre+ caract spé " pattern="(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}" autocomplete="new-password" size="30" minlength="8" maxlength="30" required>
                    <span class="seePass"><i class="fa-solid fa-eye-slash"></i><i class="fa-solid fa-eye"></i></span>
                </div>

                <label for="passwordConfirm">Confirmation mot de passe</label>
                <input type="password" id="passwordConfirm" name="passwordConfirm" pattern="(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}" size="30" minlength="8" maxlength="30" required>
            </div>
        </div>

        <input class="bouton" type="submit" value="Valider">

    </fieldset>

</form>