<h1>Se connecter !</h1>

<?php require_once('errors.inc.phtml'); ?>

<form action="index.php?route=user&action=checkAndConnect" method="POST">
        <fieldset>
                <div class="formAdmin">
                        <diV class="grid">
                                <label for="email">Entrez votre email</label>
                                <input type="email" id='email' name="email" maxlength="50" value="<?php echo htmlspecialchars(isset($_POST['email'])) ?   htmlspecialchars($_POST['email']) : ""; ?>">

                                <label for="password">Entrez votre mot de passe</label>
                                <div>
                                        <input type="password" id="password" name="password" autocomplete="current-password" maxlength="30">
                                        <span class="seePass"><i class="fa-solid fa-eye-slash"></i><i class="fa-solid fa-eye"></i></span>
                                </div>
                        </diV>
                </div>
                <input id="token" name="token" type="hidden" value="<?= $data['input'] ?>">
                <input class="bouton" type="submit" value="Valider">
        </fieldset>
</form>