<div class="homePage wrapper">
    <?php require_once('errors.inc.phtml'); ?>
    <h1>
        Le miel dans tous ses états
    </h1>

    <!-- La dernière news est mise en avant : elle apparait avant le slider -->
    <?php if (isset($data['input']['news']) && ($data['input']['news'] !== "")) : ?>

        <article class="blockLast">
            <?php if (isset($data['input']['last']["title"]) && (($data['input']['last']["title"]) !== "")) : ?>
                <h2><?= htmlspecialchars($data['input']['last']["title"]); ?></h2>
            <?php endif; ?>
            <p class="content last">
                <small> News N° <?= htmlspecialchars($data['input']['last']["id_news"]); ?> du <?= htmlspecialchars(date_format(date_create($data['input']['last']["date"]), 'd/m/y')); ?></small><br>
                <?= nl2br((htmlspecialchars($data['input']['last']["text"])), false); ?>
            </p>
            <!-- condition si pas de photo -->
            <?php if ((($data['input']['last']['picture'])) !== '') : ?>
                <img class="imgNews" src=' public/uploads/<?= htmlspecialchars($data['input']['last']['picture']); ?>' alt="photo <?= htmlspecialchars($data['input']['last']["title"]); ?>">
            <?php endif; ?>
        </article>

    <?php endif; ?>

    <!-- slider -->
    <?php if (isset($data['input']['pics']) && ($data['input']['pics'] !== "")) : ?>
        <div class="sliderSlick">
            <?php foreach (($data['input']['pics']) as $key => $valeur) : ?>
                <div>
                    <img src=" public/uploads/<?= htmlspecialchars($valeur["picture"]); ?>" alt="<?= htmlspecialchars($valeur["description"]); ?>">
                </div>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>


    <!-- Les 5 news suivants la première et actives sont affichées -->
    <?php if (isset($data['input']['news']) && ($data['input']['news'] !== "")) : ?>
        <?php foreach ($data['input']['news'] as $key => $news) : ?>
            <article class="news">
                <?php if (htmlspecialchars($news["title"]) !== "") : ?>
                    <h2><?= htmlspecialchars($news["title"]); ?></h2>
                <?php endif; ?>
                <?php if (htmlspecialchars($news["text"]) !== "") : ?>
                    <p>
                        <?= nl2br((htmlspecialchars($news["text"])), false); ?>
                    </p>
                <?php endif; ?>
                <!-- condition si pas de photo -->
                <?php if ((($news['picture'])) !== '') : ?>
                    <img class="imgNews" src=' public/uploads/<?= htmlspecialchars($news['picture']); ?>' alt="photo <?= htmlspecialchars($news["title"]); ?>">
                <?php endif; ?>
                <!-- fin traitement affichage  photo -->
            </article>
        <?php endforeach; ?>
    <?php endif; ?>
</div>