<section class="pageSalesPoints wrapper">
    <h1>Mes partenaires </h1>

    <div class="mapWrapper">
        <iframe src="https://www.google.com/maps/d/embed?mid=11Bd7hZdAqubLcEmemkGruEBJcjh4qHw&ehbc=2E312F"></iframe>
    </div>

    <div class="textSalesPoints">
        <P>Vous pouvez retrouver mes différents produits en vente dans une trentaine de lieux différents : <P>
        <p>Commequiers / Saint-Gilles-Croix-de-Vie / Challans / Bretignolles-sur-mer / La Roche-sur-Yon / Martinet / Le Fenouiller / Apremont / Soullans / Saint-Révérend / Maché / Saint-Jean-de-Monts Saint-Hilaire-de-Riez / Saint-Christophe-du-Ligneron / Coex / Landevieille / Les Sables-d'Olonne / Aizenay</p>
    </div>
    
</section>