<div class="pageZoom wrapper">
    <H1>Découvrez notre univers :</H1>

    <section>
        <h2>Les Miels</h2>
        <img src="public/medias/img/miel-sur-cuillere.jpg" alt="miel">
        <p>
            Le <strong>miel</strong> est une substance sucrée élaborée par les abeilles à miel à partir de <strong>nectar</strong> ou de <strong>miellat</strong>.
            Elles l'entreposent dans la ruche et s'en nourrissent tout au long de l'année, en particulier lors de périodes climatiques 
            défavorables. Il est aussi consommé par d'autres espèces animales dont l'espèce humaine qui organise sa production par l'élevage des abeilles à miel.
        </p>
        <p>
            Les abeilles butineuses sont chargées de l'approvisionnement de la ruche.
            Une fois posée sur une plante à fleurs l'abeille en écarte les pétales, plonge sa tête à l'intérieur, allonge sa langue et aspire le nectar qu'elle stocke provisoirement dans son jabot social. Du fait de leur anatomie et en particulier de la longueur de leur langue, les abeilles ne peuvent récolter le nectar que sur certaines fleurs, qui sont dites alors mellifères.
        </p>
        <p>
            Les abeilles peuvent aussi récolter du miellat, excrétion produite par des insectes suceurs à partir de la sève des arbres.
            Il sera utilisé de la même façon que le nectar de fleur (c'est ce produit de base qui est notamment utilisé pour élaborer le miel de sapin).

        </p>
        <div class="clear"></div>
        <p class="center">
            <a class="bouton" href="index.php?route=products&action=displayProductsOfOneCategory&cat=1">Retrouvez nos miels</a>
        </p>

    </section>

    <section>
        <h2>Les Aromiels</h2>

        <img src="public/medias/img/citron.jpg" alt="aromiels">
        <p>Un <strong>aromiel</strong> nait du mariage d'un miel et d'un ou plusieurs composés végétaux.
            Ce mariage confère au mélange un goût et des propriétés particulières.
        </p>
        <p>L’aromiel citron, aromiel onctueux aux grains fins, utilisé en cuisine, en infusion, avec des laitages ou simplement sur une tartine, l’huile essentielle de citron apporte une touche fraîche et tonique.</p>
        <p> L’aromiel noisette, avec sa texture onctueuse aux grains fins vous surprendra par son coté gourmand. L’essayer, c’est l’adopter !</p>

        <div class="clear"></div>
        <p class="center">
            <a class="bouton" href="index.php?route=products&action=displayProductsOfOneCategory&cat=2">Retrouvez nos aromiels</a>
        </p>
    </section>

    <section>
        <h2>Le Nougat</h2>

        <img src="public/medias/img/nougat-amandes.jpg" alt="nougat">
        <p>Le <strong>nougat</strong> est une confiserie originaire des pays du bassin méditerranéen.
            Il contient du miel ou du sucre, des fruits à coque ou des fruits secs, entiers, cassés ou moulus (amandes, pistaches, noix, etc.) et des parfums.
        </p>
        <p>Traditionnellement, miel et sucre sont fondus et cuits au bain-marie dans les chaudrons en cuivre avec addition des blancs d'œufs montés en neige. Ce mélange est ensuite stabilisé par l'incorporation de sucre préalablement porté à haute température, stabilisation qui donnera, après cuisson définitive, cet aspect de pâte levée caractérisant le nougat. L'incorporation des amandes et des pistaches grillées se fait en fin de cuisson.</p>
        <p>L'incorporation des amandes et des pistaches grillées se fait en fin de cuisson.</p>

        <div class="clear"></div>
        <p class="center">
            <a class="bouton" href="index.php?route=products&action=displayProductsOfOneCategory&cat=4">Retrouvez notre nougat</a>
        </p>

    </section>

    <section>
        <h2>Les Billes de miel</h2>

        <img src="public/medias/img/cuillere-canelle.jpg" alt="billes de miels">
        <p>Les <strong>billes de miel</strong> représentent certainement le forme la plus gourmande des produits issus du miel. A sucer lentement pour en savourer toutes les subtilités, elles combleront les petits gourmands …… comme les plus grands . </p>
        <P>Pour un plaisir durable, prenez le précaution de les conserver au sec et au frais.</P>
        <p>Comme pour toutes les confiserie de petite taille, les billes de miel ne sont pas recommandées pour les jeunes enfants (risque d'étouffement</p>

        <div class="clear"></div>
        <p class="center">
            <a class="bouton" href="index.php?route=products&action=displayProductsOfOneCategory&cat=5">Retrouvez nos billes de miel</a>
        </p>

    </section>

</div>