<!-- <div class="my-flipster">
    <ul>
        ?php foreach (($data['input']['pics']) as $key => $valeur) : ?>
            <li>
                <img src="public/uploads/?= htmlspecialchars($valeur["picture"]); ?>" ' 
                    alt="?= htmlspecialchars($valeur["description"]); ?>">
            </li>
        ?php endforeach; ?>
    </ul>
</div> -->

<div class="sliderSlick">
    <?php foreach (($data['input']['pics']) as $key => $valeur) : ?>
        <div >
            <img src=" public/uploads/<?= htmlspecialchars($valeur["picture"]); ?>" ' alt="<?= htmlspecialchars($valeur["description"]); ?>">
</div>
<?php endforeach; ?>
</div>