<!-- $token = $data['input'][0]; -->
<?php if (isset((($_SESSION['user'])['role'])) && (!empty($_SESSION['user'])) && (($_SESSION['user'])['role']) === 'admin' && (($_SESSION['user'])['status']) === 'actif') : ?>

    <h1> images du carroussel</h1>
    <?php require_once('./public/views/errors.inc.phtml'); ?>
    <div class="modal-window">
    </div>
    <a class="bouton" href="index.php?route=carouselsPics&action=displayFormAddPic">ajouter une image</a>


    <table class='catalog'>
        <thead>
            <tr>
                <th>description</th>
                <th>statut</th>
                <th>image</th>
                <th></th>
                <th></th>
            </tr>
        </thead>


        <tbody>
            <?php foreach ($data['input']['values'] as $key => $valeur) : ?>
                <tr>
                    <td><?= htmlspecialchars($valeur["description"]); ?> </td>
                    <td><?= htmlspecialchars($valeur["status"]); ?></td>

                    <td class="modal-trigger"><img class="vignette" src=' public/uploads/<?= htmlspecialchars($valeur['picture']); ?>' alt=" produit">
                    </td>

                    <td>
                        <a class="bouton" href="?route=carouselsPics&action=modifyPic&id=<?= htmlspecialchars($valeur['id_carousel']); ?>">Modifier</a>
                    </td>
                    <td>
                        <form class="formDelete" action="?route=carouselsPics&action=deletePic" method="post">
                            <input type="hidden" name="token" value="<?= htmlspecialchars($data['input']['token'][$valeur['id_carousel']]); ?>">
                            <input type="hidden" name="id" value="<?= htmlspecialchars($valeur['id_carousel']); ?>">
                            <input type="button" class="bouton" value="Supprimer">
                        </form>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

<?php else : ?>
    <h2> Affichage non autorisé </h2>
<?php endif; ?>