<?php if (isset((($_SESSION['user'])['role'])) && (!empty($_SESSION['user'])) && (($_SESSION['user'])['role']) === 'admin' && (($_SESSION['user'])['status']) === 'actif') : ?>

    <h1>Nouveau Produit</h1>
    <small class="asterisk">(Les champs marqués avec une * sont obligatoires)</small>

    <?php require_once('public/views/errors.inc.phtml'); ?>

    <form class="formAdmin" method="post" enctype="multipart/form-data" action=" ?route=Products&action=AddOrModifyProductProcess">

        <input id="token" name="token" type="hidden" value="<?= $data['input'][0] ?>">

        <div class="grid">
            <label for="category">Categorie<span class="star">*</span></label>
            <select name="category" id="category" autofocus>
                <?php foreach ($data['input'][1] as $key => $valeur) : ?>
                    <option value="<?= htmlspecialchars($valeur["id_category"]); ?>"><?= htmlspecialchars($valeur["categoryName"]); ?></option>
                <?php endforeach; ?>
            </select>

            <label for="productName">Nom du produit<span class="star">*</span></label>
            <input type="text" id="productName" name="productName" maxlength="100" placeholder="nom du produit" required>

            <label for="reference">Reférence<span class="star">*</span></label>
            <input type="text" id="reference" name="reference" maxlength="50" placeholder="référence de produit" required>

            <label for="teaser">Description courte </label>
            <input type="text" id="teaser" name="teaser" maxlength="255" placeholder="description courte 1 seule ligne">

            <label for="description">Description</label>
            <textarea name="description" id="description" maxlength="2000" placeholder="description du produit"></textarea>

            <label for="infos">Infos</label>
            <input type="text" id="infos" name="infos" maxlength="150" placeholder="infos">

            <label for="uploadImage">Photo<?php include "infoImg.phtml" ?></label>
            <!-- attention ecoute d'évenement sur l'input pour le preview  -->
            <input type="file" id="uploadImage" name="picture" accept="image/*">
        </div>

        <fieldset>
            <div class="grid">
                <span class="right">Produit actif ?</span>
                <div>
                    <label class="radio" for="actif">Actif</label>
                    <input type="radio" id="actif" name="status" value="actif" checked>
                    <label class="radio" for="actif">Inactif</label>
                    <input type="radio" id="inactif" name="status" value="inactif">
                </div>
            </div>

        </fieldset>

        <div class="preview">
        </div>

        <input class="bouton" type="submit" value="enregistrement">

    </form>
    <div>
        <a class="bouton" href="index.php?route=products&action=displayFormProducts">Abandon</a>
    </div>

<?php else : ?>
    <h2> Affichage non autorisé </h2>
<?php endif; ?>