<?php if (isset((($_SESSION['user'])['role'])) && (!empty($_SESSION['user'])) && (($_SESSION['user'])['role']) === 'admin' && (($_SESSION['user'])['status']) === 'actif') : ?>

    <h1>Modification d'un produit</h1>
    <small class="asterisk">(Les champs marqués avec une * sont obligatoires)</small>

    <!-- affichage eventuel des erreurs -->
    <?php require_once('public/views/errors.inc.phtml'); ?>
    <!-- pour affichage en grand des vignettes -->
    <div class="modal-window"></div>
    

    <form class="formAdmin" method="post" enctype="multipart/form-data" action=" ?route=Products&action=AddOrModifyProductProcess">

        <input id="token" name="token" type="hidden" value="<?= $data['input'][0] ?>">
        <input id="id" name="id" type="hidden" value="<?= htmlspecialchars($data['input'][2]["id_product"]); ?>">

        <div class="grid">
            <label for="category">Categorie<span class="star">*</span></label>
            <select name="category" id="category">
                <?php foreach ($data['input'][1] as $key => $valeur) : ?>
                    <option value="<?= htmlspecialchars($valeur["id_category"]); ?>" <?php if (($data['input'][2]["id_category"]) === ($valeur["id_category"])) echo "selected"; ?>><?= htmlspecialchars($valeur["categoryName"]); ?></option>
                <?php endforeach; ?>
            </select>


            <label for="productName">Nom du produit<span class="star">*</span></label>
            <input type="text" id="productName" name="productName" maxlength="100" required value="<?= htmlspecialchars($data['input'][2]["productName"]); ?>" placeholder="le nom du produit">

            <label for="reference">Reférence<span class="star">*</span></label>
            <input type="text" id="reference" name="reference" maxlength="50" required value="<?= htmlspecialchars($data['input'][2]["productRef"]); ?>" placeholder="la référence de produit">

            <label for="teaser">Description courte</label>
            <input type="text" id="teaser" name="teaser" maxlength="255" value="<?= htmlspecialchars($data['input'][2]["teaser"]); ?>" placeholder="description courte 1 seule ligne">

            <label for="description">Description</label>
            <textarea name="description" id="description" maxlength="2000" placeholder="la description du produit"><?= htmlspecialchars($data['input'][2]["description"]); ?></textarea>

            <label for="infos">Infos</label>
            <input type="text" id="infos" name="infos" maxlength="150" value="<?= htmlspecialchars($data['input'][2]["infos"] ?? ""); ?>" placeholder="infos">

            <span class="news">Photo existante</span>
            <span class="modal-trigger">
                <img class="vignette" id="pic" src='public/uploads/<?= htmlspecialchars($data['input'][2]['picture'] ?? ""); ?>' alt="produit">
            </span>

            <label for="uploadImage">Nouvelle photo ? <?php include "infoImg.phtml" ?></label>
            <input type="file" id="uploadImage" name="picture">
            <!-- Pour pouvoir recuperer l'ancienne photo si pas de changement -->
            <input type="hidden" id="photo_recup" name="photo_recup" value="<?= htmlspecialchars($data['input'][2]['picture']); ?>">

        </div>


        <fieldset>
            <div class="grid">
                <span class="right">Produit actif? </span>
                <div>
                    <label class="radio" for="actif">Actif</label>
                    <input type="radio" id="actif" name="status" value="actif" <?php if (($data['input'][2]["status"]) === ("actif")) echo "checked"; ?>>
                    <label class="radio" for="actif">Inactif</label>
                    <input type="radio" id="inactif" name="status" value="inactif" <?php if (($data['input'][2]["status"]) === ("inactif")) echo "checked"; ?>>
                </div>
            </div>
        </fieldset>

        <div class="preview">
        </div>
        <input class="bouton" type="submit" value="enregistrement">
    </form>
    <div>
        <a class="bouton" href="index.php?route=products&action=displayFormProducts">Retour</a>
    </div>

<?php else : ?>
    <h2> Affichage non autorisé </h2>
<?php endif; ?>